version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: kafka
    ports:
      - "7203:7203"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      ZOOKEEPER_IP: zookeeper
      ZOOKEEPER_PORT: 2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  kafka-websocket:
    build: kafka-websocket
    environment:
      KAFKA_HOST: kafka:9092
    ports: 
      - "9999:9999"
    volumes:
      - ./kafka-websocket:/usr/code
    depends_on:
      - kafka
  redis:
    image: "redis:alpine"
    ports: 
      - "6379:6379"
  redisCommander:
    image: tenstartups/redis-commander
    command: --redis-host redis
    depends_on:
      - redis
    ports:
      - "4567:8081"
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5431:5432"
    environment:
        POSTGRES_PASSWORD: coins
        POSTGRES_USER: coins
  scrapers:
    build: scrapers
    volumes:
      - ./scrapers:/usr/code
    environment:
      REDIS_HOST: redis
      KAFKA_HOST: kafka
  dashboard:
    build: dashboard
    ports:
      - "18080:8080"
    volumes:
      - ./dashboard:/usr/code
