version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
      ZOOKEEPER_IP: zookeeper
      ZOOKEEPER_PORT: 2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  kafka-websocket:
    build: kafka-websocket
    ports: 
      - "7080:7080"
  redis:
    image: "redis:alpine"
  redis-browser:
    image: birkof/redis-browser
    command: --url redis://redis:6379 --bind 0.0.0.0
    ports:
      - "4567:4567"
    depends_on:
      - redis
  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5431:5432"
    environment:
        POSTGRES_PASSWORD: coins
        POSTGRES_USER: coins
  scrapers:
    build: scrapers
    volumes:
      - ./scrapers:/usr/code
  dashboard:
    build: dashboard
    ports:
      - "18080:8080"
    volumes:
      - ./dashboard:/usr/code
